### ISSUE TITLE
Kill New Outlook once and run old Calendar

### ISSUE THREAD

**Issue by HalBenHB** [thepastafarian/New-Outlook-Killer#2]
Hi, I just wanted to suggest an improvement to speed up my workflow one more step.

If new Outlook is not installed, old Calendar (and Mail) apps work seamlessly. If new Outlook is installed, well, the old apps just redirect to the new one. What I do to use the old calendar application is to first uninstall the new Outlook by typing NOK in Windows Search and running it. Then I type calendar and open the old Calendar application. Then I also quit NOK from the taskbar because I don't like the idea of having an application running in the background all the time, a resource-saving habit inherited from using an old computer.

So instead of running NOK all the time, I think it would be more efficient if it would just uninstall the new Outlook once, and then run the calendar (or mail, if you prefer), and then finish its execution.

**Comment by thepastafarian** [comment]
There's a few reasons I built it the way I did. If you put the shortcut to it in the startup folder (instructions in the readme) it will automatically run when you boot up the pc and will remove new outlook before you launch the mail/calendar app, zero user input required.

As for the constant running: new outlook is such aggressive malware, it's baked into the code for both the mail app and calendar to reistall new outlook after just 2 lauches of either mail or calendar and to open it after 3. So that means if you just run the script once and then stop it, then launch the mail or calendar apps 3 times in the same session then new outlook will be reinstalled and the old apps will redirect you anyway. Additionally Microsoft tries to install new outlook during Windows updates as well as seemingly random intervals when mail and calendar are running.

I understand not wanting a program constantly running in the background but that's legitimately the only way that I could make the program reliable. Thankfully the length of the script means that it is a very lightweight program. it does have a resource monitor in the tool bar but the program uses so few resources that the monitor doesn't work quite right, so that will be something I will work on in the future.

By not having it run on startup and by stopping NOK after lauching mail or calendar you're removing all the automation. At that point it's easier to just run this powershell script when you want it to uninstall new outlook:

powershell "Get-AppxPackage *Outlook* | Remove-AppxPackage"

-------- Original message --------
From: HalBenHB ***@***.***>
Date: 11/5/24 15:47 (GMT+02:00)
To: thepastafarian/New-Outlook-Killer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [thepastafarian/New-Outlook-Killer] Kill New Outlook once and run old Calendar (Issue #2)


Hi, I just wanted to suggest an improvement to speed up my workflow one more step.

If new Outlook is not installed, old Calendar (and Mail) apps work seamlessly. If new Outlook is installed, well, the old apps just redirect to the new one. What I do to use the old calendar application is to first uninstall the new Outlook by typing NOK in Windows Search and running it. Then I type calendar and open the old Calendar application. Then I also quit NOK from the taskbar because I don't like the idea of having an application running in the background all the time, a resource-saving habit inherited from using an old computer.

So instead of running NOK all the time, I think it would be more efficient if it would just uninstall the new Outlook once, and then run the calendar (or mail, if you prefer), and then finish its execution.
